// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: android_imgtools/partition_tools/dynamic_partitions_device_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Android {

  /// <summary>Holder for reflection information generated from android_imgtools/partition_tools/dynamic_partitions_device_info.proto</summary>
  public static partial class DynamicPartitionsDeviceInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for android_imgtools/partition_tools/dynamic_partitions_device_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicPartitionsDeviceInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkVhbmRyb2lkX2ltZ3Rvb2xzL3BhcnRpdGlvbl90b29scy9keW5hbWljX3Bh",
            "cnRpdGlvbnNfZGV2aWNlX2luZm8ucHJvdG8SB2FuZHJvaWQiqgUKIER5bmFt",
            "aWNQYXJ0aXRpb25zRGV2aWNlSW5mb1Byb3RvEg8KB2VuYWJsZWQYASABKAgS",
            "EAoIcmV0cm9maXQYAiABKAgSRwoKcGFydGl0aW9ucxgDIAMoCzIzLmFuZHJv",
            "aWQuRHluYW1pY1BhcnRpdGlvbnNEZXZpY2VJbmZvUHJvdG8uUGFydGl0aW9u",
            "Ej8KBmdyb3VwcxgEIAMoCzIvLmFuZHJvaWQuRHluYW1pY1BhcnRpdGlvbnNE",
            "ZXZpY2VJbmZvUHJvdG8uR3JvdXASWwoNYmxvY2tfZGV2aWNlcxgFIAMoCzI1",
            "LmFuZHJvaWQuRHluYW1pY1BhcnRpdGlvbnNEZXZpY2VJbmZvUHJvdG8uQmxv",
            "Y2tEZXZpY2VSDWJsb2NrX2RldmljZXMatQEKCVBhcnRpdGlvbhIMCgRuYW1l",
            "GAEgASgJEh4KCmdyb3VwX25hbWUYAiABKAlSCmdyb3VwX25hbWUSHgoKaXNf",
            "ZHluYW1pYxgDIAEoCFIKaXNfZHluYW1pYxIMCgRzaXplGAQgASgEEhgKB2Zz",
            "X3NpemUYBSABKARSB2ZzX3NpemUSGAoHZnNfdXNlZBgGIAEoBFIHZnNfdXNl",
            "ZBIYCgdmc190eXBlGAcgASgJUgdmc190eXBlGjkKBUdyb3VwEgwKBG5hbWUY",
            "ASABKAkSIgoMbWF4aW11bV9zaXplGAIgASgEUgxtYXhpbXVtX3NpemUaiAEK",
            "C0Jsb2NrRGV2aWNlEgwKBG5hbWUYASABKAkSDAoEc2l6ZRgCIAEoBBIeCgpi",
            "bG9ja19zaXplGAMgASgEUgpibG9ja19zaXplEhEKCWFsaWdubWVudBgEIAEo",
            "BBIqChBhbGlnbm1lbnRfb2Zmc2V0GAUgASgEUhBhbGlnbm1lbnRfb2Zmc2V0",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Android.DynamicPartitionsDeviceInfoProto), global::Android.DynamicPartitionsDeviceInfoProto.Parser, new[]{ "Enabled", "Retrofit", "Partitions", "Groups", "BlockDevices" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition), global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition.Parser, new[]{ "Name", "GroupName", "IsDynamic", "Size", "FsSize", "FsUsed", "FsType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Android.DynamicPartitionsDeviceInfoProto.Types.Group), global::Android.DynamicPartitionsDeviceInfoProto.Types.Group.Parser, new[]{ "Name", "MaximumSize" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice), global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice.Parser, new[]{ "Name", "Size", "BlockSize", "Alignment", "AlignmentOffset" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Next: 6
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DynamicPartitionsDeviceInfoProto : pb::IMessage<DynamicPartitionsDeviceInfoProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DynamicPartitionsDeviceInfoProto> _parser = new pb::MessageParser<DynamicPartitionsDeviceInfoProto>(() => new DynamicPartitionsDeviceInfoProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DynamicPartitionsDeviceInfoProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Android.DynamicPartitionsDeviceInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicPartitionsDeviceInfoProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicPartitionsDeviceInfoProto(DynamicPartitionsDeviceInfoProto other) : this() {
      enabled_ = other.enabled_;
      retrofit_ = other.retrofit_;
      partitions_ = other.partitions_.Clone();
      groups_ = other.groups_.Clone();
      blockDevices_ = other.blockDevices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicPartitionsDeviceInfoProto Clone() {
      return new DynamicPartitionsDeviceInfoProto(this);
    }

    /// <summary>Field number for the "enabled" field.</summary>
    public const int EnabledFieldNumber = 1;
    private bool enabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Enabled {
      get { return enabled_; }
      set {
        enabled_ = value;
      }
    }

    /// <summary>Field number for the "retrofit" field.</summary>
    public const int RetrofitFieldNumber = 2;
    private bool retrofit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Retrofit {
      get { return retrofit_; }
      set {
        retrofit_ = value;
      }
    }

    /// <summary>Field number for the "partitions" field.</summary>
    public const int PartitionsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition> _repeated_partitions_codec
        = pb::FieldCodec.ForMessage(26, global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition.Parser);
    private readonly pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition> partitions_ = new pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Partition> Partitions {
      get { return partitions_; }
    }

    /// <summary>Field number for the "groups" field.</summary>
    public const int GroupsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Android.DynamicPartitionsDeviceInfoProto.Types.Group> _repeated_groups_codec
        = pb::FieldCodec.ForMessage(34, global::Android.DynamicPartitionsDeviceInfoProto.Types.Group.Parser);
    private readonly pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Group> groups_ = new pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Group>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.Group> Groups {
      get { return groups_; }
    }

    /// <summary>Field number for the "block_devices" field.</summary>
    public const int BlockDevicesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice> _repeated_blockDevices_codec
        = pb::FieldCodec.ForMessage(42, global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice.Parser);
    private readonly pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice> blockDevices_ = new pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Android.DynamicPartitionsDeviceInfoProto.Types.BlockDevice> BlockDevices {
      get { return blockDevices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DynamicPartitionsDeviceInfoProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DynamicPartitionsDeviceInfoProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Enabled != other.Enabled) return false;
      if (Retrofit != other.Retrofit) return false;
      if(!partitions_.Equals(other.partitions_)) return false;
      if(!groups_.Equals(other.groups_)) return false;
      if(!blockDevices_.Equals(other.blockDevices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Enabled != false) hash ^= Enabled.GetHashCode();
      if (Retrofit != false) hash ^= Retrofit.GetHashCode();
      hash ^= partitions_.GetHashCode();
      hash ^= groups_.GetHashCode();
      hash ^= blockDevices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Enabled != false) {
        output.WriteRawTag(8);
        output.WriteBool(Enabled);
      }
      if (Retrofit != false) {
        output.WriteRawTag(16);
        output.WriteBool(Retrofit);
      }
      partitions_.WriteTo(output, _repeated_partitions_codec);
      groups_.WriteTo(output, _repeated_groups_codec);
      blockDevices_.WriteTo(output, _repeated_blockDevices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Enabled != false) {
        output.WriteRawTag(8);
        output.WriteBool(Enabled);
      }
      if (Retrofit != false) {
        output.WriteRawTag(16);
        output.WriteBool(Retrofit);
      }
      partitions_.WriteTo(ref output, _repeated_partitions_codec);
      groups_.WriteTo(ref output, _repeated_groups_codec);
      blockDevices_.WriteTo(ref output, _repeated_blockDevices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Enabled != false) {
        size += 1 + 1;
      }
      if (Retrofit != false) {
        size += 1 + 1;
      }
      size += partitions_.CalculateSize(_repeated_partitions_codec);
      size += groups_.CalculateSize(_repeated_groups_codec);
      size += blockDevices_.CalculateSize(_repeated_blockDevices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DynamicPartitionsDeviceInfoProto other) {
      if (other == null) {
        return;
      }
      if (other.Enabled != false) {
        Enabled = other.Enabled;
      }
      if (other.Retrofit != false) {
        Retrofit = other.Retrofit;
      }
      partitions_.Add(other.partitions_);
      groups_.Add(other.groups_);
      blockDevices_.Add(other.blockDevices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Enabled = input.ReadBool();
            break;
          }
          case 16: {
            Retrofit = input.ReadBool();
            break;
          }
          case 26: {
            partitions_.AddEntriesFrom(input, _repeated_partitions_codec);
            break;
          }
          case 34: {
            groups_.AddEntriesFrom(input, _repeated_groups_codec);
            break;
          }
          case 42: {
            blockDevices_.AddEntriesFrom(input, _repeated_blockDevices_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Enabled = input.ReadBool();
            break;
          }
          case 16: {
            Retrofit = input.ReadBool();
            break;
          }
          case 26: {
            partitions_.AddEntriesFrom(ref input, _repeated_partitions_codec);
            break;
          }
          case 34: {
            groups_.AddEntriesFrom(ref input, _repeated_groups_codec);
            break;
          }
          case 42: {
            blockDevices_.AddEntriesFrom(ref input, _repeated_blockDevices_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DynamicPartitionsDeviceInfoProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Next: 8
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Partition : pb::IMessage<Partition>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Partition> _parser = new pb::MessageParser<Partition>(() => new Partition());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Partition> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Android.DynamicPartitionsDeviceInfoProto.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Partition() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Partition(Partition other) : this() {
          name_ = other.name_;
          groupName_ = other.groupName_;
          isDynamic_ = other.isDynamic_;
          size_ = other.size_;
          fsSize_ = other.fsSize_;
          fsUsed_ = other.fsUsed_;
          fsType_ = other.fsType_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Partition Clone() {
          return new Partition(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "group_name" field.</summary>
        public const int GroupNameFieldNumber = 2;
        private string groupName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string GroupName {
          get { return groupName_; }
          set {
            groupName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "is_dynamic" field.</summary>
        public const int IsDynamicFieldNumber = 3;
        private bool isDynamic_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool IsDynamic {
          get { return isDynamic_; }
          set {
            isDynamic_ = value;
          }
        }

        /// <summary>Field number for the "size" field.</summary>
        public const int SizeFieldNumber = 4;
        private ulong size_;
        /// <summary>
        ///* Total size of all extents on super partition 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Size {
          get { return size_; }
          set {
            size_ = value;
          }
        }

        /// <summary>Field number for the "fs_size" field.</summary>
        public const int FsSizeFieldNumber = 5;
        private ulong fsSize_;
        /// <summary>
        ///* Total size of the filesystem. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong FsSize {
          get { return fsSize_; }
          set {
            fsSize_ = value;
          }
        }

        /// <summary>Field number for the "fs_used" field.</summary>
        public const int FsUsedFieldNumber = 6;
        private ulong fsUsed_;
        /// <summary>
        ///* Used space of the filesystem. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong FsUsed {
          get { return fsUsed_; }
          set {
            fsUsed_ = value;
          }
        }

        /// <summary>Field number for the "fs_type" field.</summary>
        public const int FsTypeFieldNumber = 7;
        private string fsType_ = "";
        /// <summary>
        ///*  Name of the filesystem. 
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string FsType {
          get { return fsType_; }
          set {
            fsType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Partition);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Partition other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (GroupName != other.GroupName) return false;
          if (IsDynamic != other.IsDynamic) return false;
          if (Size != other.Size) return false;
          if (FsSize != other.FsSize) return false;
          if (FsUsed != other.FsUsed) return false;
          if (FsType != other.FsType) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (GroupName.Length != 0) hash ^= GroupName.GetHashCode();
          if (IsDynamic != false) hash ^= IsDynamic.GetHashCode();
          if (Size != 0UL) hash ^= Size.GetHashCode();
          if (FsSize != 0UL) hash ^= FsSize.GetHashCode();
          if (FsUsed != 0UL) hash ^= FsUsed.GetHashCode();
          if (FsType.Length != 0) hash ^= FsType.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (GroupName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(GroupName);
          }
          if (IsDynamic != false) {
            output.WriteRawTag(24);
            output.WriteBool(IsDynamic);
          }
          if (Size != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(Size);
          }
          if (FsSize != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(FsSize);
          }
          if (FsUsed != 0UL) {
            output.WriteRawTag(48);
            output.WriteUInt64(FsUsed);
          }
          if (FsType.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(FsType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (GroupName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(GroupName);
          }
          if (IsDynamic != false) {
            output.WriteRawTag(24);
            output.WriteBool(IsDynamic);
          }
          if (Size != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(Size);
          }
          if (FsSize != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(FsSize);
          }
          if (FsUsed != 0UL) {
            output.WriteRawTag(48);
            output.WriteUInt64(FsUsed);
          }
          if (FsType.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(FsType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (GroupName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupName);
          }
          if (IsDynamic != false) {
            size += 1 + 1;
          }
          if (Size != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Size);
          }
          if (FsSize != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FsSize);
          }
          if (FsUsed != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FsUsed);
          }
          if (FsType.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(FsType);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Partition other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.GroupName.Length != 0) {
            GroupName = other.GroupName;
          }
          if (other.IsDynamic != false) {
            IsDynamic = other.IsDynamic;
          }
          if (other.Size != 0UL) {
            Size = other.Size;
          }
          if (other.FsSize != 0UL) {
            FsSize = other.FsSize;
          }
          if (other.FsUsed != 0UL) {
            FsUsed = other.FsUsed;
          }
          if (other.FsType.Length != 0) {
            FsType = other.FsType;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                GroupName = input.ReadString();
                break;
              }
              case 24: {
                IsDynamic = input.ReadBool();
                break;
              }
              case 32: {
                Size = input.ReadUInt64();
                break;
              }
              case 40: {
                FsSize = input.ReadUInt64();
                break;
              }
              case 48: {
                FsUsed = input.ReadUInt64();
                break;
              }
              case 58: {
                FsType = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                GroupName = input.ReadString();
                break;
              }
              case 24: {
                IsDynamic = input.ReadBool();
                break;
              }
              case 32: {
                Size = input.ReadUInt64();
                break;
              }
              case 40: {
                FsSize = input.ReadUInt64();
                break;
              }
              case 48: {
                FsUsed = input.ReadUInt64();
                break;
              }
              case 58: {
                FsType = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Next: 3
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Group : pb::IMessage<Group>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Group> _parser = new pb::MessageParser<Group>(() => new Group());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Group> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Android.DynamicPartitionsDeviceInfoProto.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Group() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Group(Group other) : this() {
          name_ = other.name_;
          maximumSize_ = other.maximumSize_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Group Clone() {
          return new Group(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "maximum_size" field.</summary>
        public const int MaximumSizeFieldNumber = 2;
        private ulong maximumSize_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong MaximumSize {
          get { return maximumSize_; }
          set {
            maximumSize_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Group);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Group other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (MaximumSize != other.MaximumSize) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (MaximumSize != 0UL) hash ^= MaximumSize.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (MaximumSize != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(MaximumSize);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (MaximumSize != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(MaximumSize);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (MaximumSize != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaximumSize);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Group other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.MaximumSize != 0UL) {
            MaximumSize = other.MaximumSize;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                MaximumSize = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                MaximumSize = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Next: 6
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class BlockDevice : pb::IMessage<BlockDevice>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<BlockDevice> _parser = new pb::MessageParser<BlockDevice>(() => new BlockDevice());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<BlockDevice> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Android.DynamicPartitionsDeviceInfoProto.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockDevice() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockDevice(BlockDevice other) : this() {
          name_ = other.name_;
          size_ = other.size_;
          blockSize_ = other.blockSize_;
          alignment_ = other.alignment_;
          alignmentOffset_ = other.alignmentOffset_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BlockDevice Clone() {
          return new BlockDevice(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "size" field.</summary>
        public const int SizeFieldNumber = 2;
        private ulong size_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Size {
          get { return size_; }
          set {
            size_ = value;
          }
        }

        /// <summary>Field number for the "block_size" field.</summary>
        public const int BlockSizeFieldNumber = 3;
        private ulong blockSize_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong BlockSize {
          get { return blockSize_; }
          set {
            blockSize_ = value;
          }
        }

        /// <summary>Field number for the "alignment" field.</summary>
        public const int AlignmentFieldNumber = 4;
        private ulong alignment_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Alignment {
          get { return alignment_; }
          set {
            alignment_ = value;
          }
        }

        /// <summary>Field number for the "alignment_offset" field.</summary>
        public const int AlignmentOffsetFieldNumber = 5;
        private ulong alignmentOffset_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong AlignmentOffset {
          get { return alignmentOffset_; }
          set {
            alignmentOffset_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as BlockDevice);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(BlockDevice other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (Size != other.Size) return false;
          if (BlockSize != other.BlockSize) return false;
          if (Alignment != other.Alignment) return false;
          if (AlignmentOffset != other.AlignmentOffset) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (Size != 0UL) hash ^= Size.GetHashCode();
          if (BlockSize != 0UL) hash ^= BlockSize.GetHashCode();
          if (Alignment != 0UL) hash ^= Alignment.GetHashCode();
          if (AlignmentOffset != 0UL) hash ^= AlignmentOffset.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (Size != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(Size);
          }
          if (BlockSize != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(BlockSize);
          }
          if (Alignment != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(Alignment);
          }
          if (AlignmentOffset != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(AlignmentOffset);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (Size != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(Size);
          }
          if (BlockSize != 0UL) {
            output.WriteRawTag(24);
            output.WriteUInt64(BlockSize);
          }
          if (Alignment != 0UL) {
            output.WriteRawTag(32);
            output.WriteUInt64(Alignment);
          }
          if (AlignmentOffset != 0UL) {
            output.WriteRawTag(40);
            output.WriteUInt64(AlignmentOffset);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (Size != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Size);
          }
          if (BlockSize != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BlockSize);
          }
          if (Alignment != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Alignment);
          }
          if (AlignmentOffset != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AlignmentOffset);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(BlockDevice other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.Size != 0UL) {
            Size = other.Size;
          }
          if (other.BlockSize != 0UL) {
            BlockSize = other.BlockSize;
          }
          if (other.Alignment != 0UL) {
            Alignment = other.Alignment;
          }
          if (other.AlignmentOffset != 0UL) {
            AlignmentOffset = other.AlignmentOffset;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                Size = input.ReadUInt64();
                break;
              }
              case 24: {
                BlockSize = input.ReadUInt64();
                break;
              }
              case 32: {
                Alignment = input.ReadUInt64();
                break;
              }
              case 40: {
                AlignmentOffset = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 16: {
                Size = input.ReadUInt64();
                break;
              }
              case 24: {
                BlockSize = input.ReadUInt64();
                break;
              }
              case 32: {
                Alignment = input.ReadUInt64();
                break;
              }
              case 40: {
                AlignmentOffset = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
